# run `swiftlint rules` for more info

reporter: xcode

included:                   # paths to include during linting
    - ../../TemplateApp

disabled_rules:             # rule identifiers to exclude from running
    - force_cast
    - force_try
    - valid_ibinspectable

opt_in_rules:               # some rules are only opt-in
    - anyobject_protocol
    - array_init
    - attributes
    - closure_body_length
    - closure_end_indentation
    - closure_spacing
    - collection_alignment
    - contains_over_filter_count
    - contains_over_filter_is_empty
    - contains_over_first_not_nil
    - convenience_type
    - discarded_notification_center_observer
    - discouraged_assert
    - empty_collection_literal
    - empty_count
    - empty_string
    - explicit_init
    - fatal_error_message
    - file_name_no_space
    - first_where
    - flatmap_over_map_reduce
    - implicit_return
    - last_where
    - legacy_multiple
    - legacy_random
    - let_var_whitespace
    - literal_expression_end_indentation
    - modifier_order
    - multiline_arguments
    - multiline_arguments_brackets
    - multiline_function_chains
    - multiline_literal_brackets
    - multiline_parameters
    - multiline_parameters_brackets
    - object_literal
    - operator_usage_whitespace
    - overridden_super_call
    - pattern_matching_keywords
    - prefer_self_type_over_type_of_self
    - prefer_zero_over_explicit_init
    - prohibited_interface_builder
    - redundant_nil_coalescing
    - redundant_type_annotation
    - redundant_void_return
    - sorted_imports
    - static_operator
    - toggle_bool
    - unneeded_parentheses_in_closure_argument
    - unused_declaration
    - unused_import
    - vertical_parameter_alignment_on_call
    - vertical_whitespace_between_cases
    - vertical_whitespace_closing_braces
    - vertical_whitespace_opening_braces
    - yoda_condition

# configurable rules can be customized from this configuration file

nesting:
  type_level:
    warning: 2

closure_body_length:
    warning: 30
    error: 50

empty_count:
    severity: warning

file_length:
    warning: 500
    error: 1000
    ignore_comment_only_lines: true

identifier_name:
    min_length:
        warning: 2
        error: 1
    max_length:
        warning: 50
        error: 60

line_length:
    ignores_function_declarations: true
    ignores_comments: true
    ignores_urls: true
    warning: 200
    error: 250

type_name:
    max_length:
        warning: 50
        error: 100

type_body_length:
    warning: 400
    error: 500

function_body_length:
    warning: 60
    error: 100

large_tuple:
    warning: 4
    error: 5
